

  mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
    
    ports:
      - "27017:27017"
      
  app:
    build: ./Infoglobo_Backend
    ports:
      - "8080:8080"
    links:
      - mongo

  #Nome da aplicação rodando
  web: 
    #Diretório do dockerfile
    build: ./Infoglobo_Frontend
    #Comando inicial
    command: npm run dev
    #Portas mapeadas
    ports: 
      - "3000:3000"
    #Diretório que será sincronizado com o container
    volumes:
      #Do diretório : Para diretório do container
      - ./Infoglobo_Frontend:/web
    links:
      - app